services:
  - type: web
    name: shopify-obs-alerts
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn project.main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PYTHONPATH
        value: "." 